
-- SKILLS: skills -> skillsetskills -> skillset
INSERT INTO project3.skills(skill_name) VALUES
	('JavaScript'),
	('React'),
	('Java'),
	('TypeScript'),
	('Spring'),
	('Maven'),
	('Redux'),
	('Microservices'),
	('Hibernate'),
	('REST'),
	('C#'),
	('.NET'),
	('Salesforce'),
	('Data Modeling'),
	('Data Analysis'),
    ('JSP'),
    ('XML'),
    ('Git'),
    ('JUnit'),
    ('JDBC'),
    ('jQuery'),
    ('AJAX'),
    ('UNIX'),
    ('AWS'),
    ('Jenkins'),
    ('SOAP'),
    ('AngularJS'),
    ('Selenium'),
    ('Cucumber'),
    ('UFT'),
    ('Python'),
    ('Robot Framework'),
    ('ALM'),
    ('SDLC'),
    ('Agile'),
    ('Testing'),
    ('VBScript'),
    ('SOAP UI'),
    ('TestNG'),
    ('Chef'),
    ('Docker'),
    ('Kafka'),
    ('NoSQL'),
    ('ASP.NET'),
    ('ADO.NET'),
    ('Entity Framework'),
    ('MSBuild'),
    ('WPF'),
    ('WCF'),
    ('J2EE'),
    ('InfoSec'),
    ('MS Office'),
    ('Pega'),
    ('Angular'),
    ('MS Visio'),
    ('Business Analysis'),
    ('Networking'),
    ('AWS Compute/Networking'),
    ('AWS Security/Monitoring'),
    ('AWS Storage/Database'),
    ('AWS Operations/Application'),
    ('AWS Orchestration'),
    ('SF Apex'),
    ('SF Visualforce'),
    ('ServiceNow Admin'),
    ('ServiceNow Developer'),
    ('SF Security & Access'),
    ('SF Data Model'),
    ('SF Process Automation'),
    ('SF Sales & Marketing'),
    ('SF Service & Support'),
    ('SF Reports/Dashboards'),
    ('SF Data Management'),
    ('SF SOQL & SOSL'),
    ('SF Lightning'),
    ('Dynamics CRM'),
    ('.NET MVC'),
    ('Problem Solving'),
    ('SF App Builder'),
    ('SF Debug & Deployment'),
    ('Hadoop'),
    ('MapReduce'),
    ('HDFS'),
    ('ZooKeeper'),
    ('Oozie'),
    ('Sqoop'),
    ('Hive'),
    ('Pig'),
    ('HBase'),
    ('Spark'),
    ('EMR'),
    ('HDInsight'),
    ('UiPath'),
    ('SF Setup'),
    ('SF Data Model'),
    ('SF Reports & Dashboards'),
    ('SF Process Automation'),
    ('SF Activities & Collaboration'),
    ('SF Data Management'),
    ('SF External Applications & AppExchange'),
    ('SF ADM201'),
    ('SF Triggers'),
    ('SF Testing'),
    ('SF Lightning'),
    ('SF API & Integration'),
    ('SF PD1'),
    ('.NET'),
    ('DevOps'),
    ('BA-Fundamentals'),
    ('Requirements Modeling & Documentation'),
    ('BA-SQL'),
    ('Agile Business Analysis'),
    ('BA-Soft skills'),
    ('BA-ECBA-Preparation'),
    ('Network Security'),
    ('Go'
    ),('JVM'),
    ('Performance Testing'),
    ('Linux'),
    ('IOS Mobile App Development'),
    ('Andriod Mobile App Development'),
    ('iOS/Swift Mobile App'),
    ('iOS Fundamentals and Architecture'),
    ('Swift 4 Fundamentals'),
    ('iOS/Swift HOL Sessions'),
    ('Android/Java Mobile App'),
    ('Android Fundamentals and Architecture'),
    ('Android HOL Sessions'),
    ('iOS Mobile App Development'),
    ('Android Mobile App Development'),
    ('Revature AP');
INSERT INTO project3.skillset (name) values
	('Java + React'),
	('Full Stack Java + Microservices'),
	('Salesforce'),
	('Cloud Technologies'),
	('RandomSkillSet'),
	('Skillset6'),
    ('Skillset7'),
    ('Skillset8'),
    ('Skillset9'),
    ('Skillset10'),
    ('Skillset11'),
    ('Skillset12');
INSERT INTO project3.skillsetskills VALUES
	(1,1),
	(1,2),
	(1,3),
	(1,4),
	(2,3),
	(2,5),
	(2,6),
	(2,8),
	(2,13),
	(3,26),
	(4,5),
	(4,3),
	(4,38),
	(4,9),
	(4,8),
	(5,5),
    (5,2),
    (5,3),
    (5,4),
    (6,3),
    (6,5),
    (6,6),
    (6,8),
    (6,23),
    (7,7),
    (7,2),
    (7,3),
    (7,4),
    (8,3),
    (8,5),
    (8,6),
    (8,8),
    (8,13),
    (9,9),
    (9,2),
    (9,3),
    (9,4),
    (10,3),
    (10,5),
    (10,10),
    (10,8),
    (10,23),
    (11,11),
    (11,2),
    (11,3),
    (11,4),
    (12,3),
    (12,5),
    (12,6),
    (12,12),
    (12,13);
	
-- CLIENT: -> client -> clientdemand

insert into project3.client  (client_id, name) values
    (1, 'Walmart'),
    (2, 'Amazon'),
    (3, 'Exxon Mobil'),
    (4, 'Apple'),
    (5, 'CVS Health'),
    (6, 'Berkshire Hathaway'),
    (7, 'UnitedHealth Group'),
    (8, 'McKesson'),
    (9, 'AT&T'),
    (10, 'AmerisourceBergen'),
    (11, 'Alphabet'),
    (12, 'Ford Motor'),
    (13, 'Cigna'),
    (14, 'Costco Wholesale');
   
 INSERT INTO project3.clientdemand VALUES
 	(default,12,'2020-07-31',1,1),
 	(default,15,'2020-08-18',2,4),
 	(default,3,'2020-10-22',3,8),
 	(default,5,'2020-11-19',4,2),
 	(default,50,'2020-08-14',5,9),
 	(default,4,'2020-07-15',6,10),
 	(default,24,'2020-10-06',7,2),
 	(default,11,'2020-07-24',8,5),
 	(default,33,'2020-12-25',9,1),
 	(default,5,'2020-09-26',10,8),
 	(default,1,'2020-10-01',11,7),
 	(default,20,'2021-01-01',12,3),
 	(default,5,'2020-08-02',2,3),
 	(default,9,'2020-07-25',4,1);

-- BATCH: associate -> location -> curriculum -> batch -> curriculumskills
INSERT INTO project3.associate (first_name,last_name,email,interview_score) VALUES
	('Jimothy','Bupkins','jbupkins@jim.bup',25),
	('Cherida','Thing','cthing0@jimdo.com',73.25),
('Brett','Rotge','brotge1@oaic.gov.au',45.25),
('Noni','Kupker','nkupker2@cafepress.com',26.75),
('Gery','June','gjune3@mashable.com',80.5),
('Hannis','Corthes','hcorthes4@printfriendly.com',40.75),
('Darbie','Heikkinen','dheikkinen5@soup.io',21.75),
('Warner','Portriss','wportriss6@1und1.de',51.75),
('Rafaellle','Delagnes','rdelagnes7@baidu.com',41.5),
('Karly','Glenwright','kglenwright8@cnet.com',43.5),
('Algernon','Hopkynson','ahopkynson9@de.vu',55.25),
('Neron','Gelletly','ngelletlya@weibo.com',12.0),
('Wheeler','Ladley','wladleyb@themeforest.net',59.25),
('Leandra','Mougeot','lmougeotc@umn.edu',84.75),
('Umeko','Dunleavy','udunleavyd@smugmug.com',47.25),
('Yolanda','McTurlough','ymcturloughe@comcast.net',99.0),
('Clevie','Baysting','cbaystingf@tmall.com',87.25),
('Dalt','Lipscombe','dlipscombeg@auda.org.au',56.0),
('Frederique','Purnell','fpurnellh@squidoo.com',2.25),
('Winnie','Leftley','wleftleyi@wufoo.com',49.75),
('Ruthie','Vallance','rvallancej@phpbb.com',86.0),
('Fanny','Rignold','frignoldk@mac.com',22.75),
('Cher','Gillinghams','cgillinghamsl@cyberchimps.com',43.25),
('Aubrette','Tremble','atremblem@purevolume.com',40.0),
('Luke','MacTrustrie','lmactrustrien@ihg.com',93.25),
('Reiko','Jopling','rjoplingo@tuttocitta.it',81.5),
('Thomasin','Broomhead','tbroomheadp@twitpic.com',62.5),
('Carlos','Mayling','cmaylingq@people.com.cn',47.5),
('Nathanael','Orton','nortonr@marriott.com',49.25),
('Brenn','Notton','bnottons@unc.edu',25.25),
('Cammy','Krystek','ckrystekt@nhs.uk',10.5),
('Agatha','Hinners','ahinnersu@ucsd.edu',41.25),
('Ailbert','Claessens','aclaessensv@cafepress.com',31.5),
('Monique','Guyet','mguyetw@plala.or.jp',58.75),
('Zacharias','Bedo','zbedox@bandcamp.com',12.5),
('Selene','Hucks','shucksy@usgs.gov',85.5),
('Rici','Sang','rsangz@theguardian.com',74.0),
('Alfonso','Calderhead','acalderhead10@vk.com',29.75),
('Murial','Geaveny','mgeaveny11@vk.com',46.5),
('Susan','Cappell','scappell12@ezinearticles.com',39.5),
('Ree','Oliva','roliva13@people.com.cn',33.0),
('Lani','Cradick','lcradick14@is.gd',43.25),
('Hashim','Raymont','hraymont15@who.int',75.75),
('Allison','Jirka','ajirka16@google.fr',54.25),
('Marchelle','Harpin','mharpin17@nydailynews.com',43.25),
('Fee','Skyrm','fskyrm18@youtu.be',43.25),
('Sibley','Thorington','sthorington19@baidu.com',75.25),
('Lynde','Fairbourne','lfairbourne1a@ucoz.ru',55.5),
('Shaine','Cramb','scramb1b@google.pl',48.5),
('Renee','Onraet','ronraet1c@japanpost.jp',35.75),
('Anallese','Earnshaw','aearnshaw1d@naver.com',61.5),
('Geoffrey','Eubank','geubank1e@so-net.ne.jp',67.25),
('Cordelia','Wohler','cwohler1f@cbc.ca',27.0),
('Hyacintha','Juste','hjuste1g@ocn.ne.jp',10.75),
('Gael','De Michetti','gdemichetti1h@seesaa.net',47.0),
('Pierrette','Ketley','pketley1i@smh.com.au',43.5),
('Ailene','Chesterman','achesterman1j@uiuc.edu',37.0),
('Chelsie','Girton','cgirton1k@rakuten.co.jp',76.25),
('Brana','Narey','bnarey1l@dagondesign.com',70.75),
('Nora','Pigden','npigden1m@posterous.com',78.5),
('Giuditta','Rosettini','grosettini1n@tumblr.com',7.5),
('Geoff','Parlet','gparlet1o@marriott.com',48.0),
('Selma','Fullerlove','sfullerlove1p@princeton.edu',72.0),
('Leila','Langman','llangman1q@cpanel.net',41.5),
('Buddy','Braunton','bbraunton1r@bluehost.com',73.75),
('Jenilee','Saggs','jsaggs1s@statcounter.com',65.0),
('Cassondra','Wallington','cwallington1t@intel.com',57.0),
('Josephine','McCallam','jmccallam1u@shutterfly.com',0.5),
('Chloette','Velte','cvelte1v@reverbnation.com',50.75),
('Hilarius','Mac Giany','hmacgiany1w@guardian.co.uk',43.75),
('Aigneis','Benka','abenka1x@qq.com',53.75),
('Cris','Pomfrett','cpomfrett1y@hugedomains.com',38.0),
('Haleigh','Spendley','hspendley1z@naver.com',58.25),
('Becca','Shane','bshane20@tinyurl.com',3.5),
('Alyssa','Bury','abury21@cnn.com',42.5),
('Tait','Clayson','tclayson22@nasa.gov',96.5),
('Jaymee','Plowright','jplowright23@wisc.edu',0.5),
('Sonny','Roydon','sroydon24@yandex.ru',43.75),
('Pearline','Pancoast','ppancoast25@cyberchimps.com',66.25),
('Flem','Baskeyfield','fbaskeyfield26@posterous.com',79.0),
('Bibbye','Rookeby','brookeby27@fda.gov',47.75),
('Dillon','Gorrick','dgorrick28@e-recht24.de',66.0),
('Osborne','Redborn','oredborn29@soundcloud.com',33.75),
('Desirae','Bhatia','dbhatia2a@quantcast.com',7.5),
('Elane','Talton','etalton2b@nytimes.com',97.75),
('Shay','Zeal','szeal2c@deliciousdays.com',87.0),
('Hayes','Giraudou','hgiraudou2d@g.co',27.0),
('Freddi','Elster','felster2e@sfgate.com',8.0),
('Cecilio','Endrici','cendrici2f@ifeng.com',47.75),
('Margi','Casella','mcasella2g@scribd.com',77.25),
('Dale','Mackstead','dmackstead2h@networkadvertising.org',95.0),
('Nicole','Joul','njoul2i@hatena.ne.jp',89.0),
('Regine','Renahan','rrenahan2j@4shared.com',36.5),
('Quinlan','Lepick','qlepick2k@jiathis.com',37.75),
('Friedrick','Saleway','fsaleway2l@histats.com',49.0),
('Guillema','Shadbolt','gshadbolt2m@businessinsider.com',2.75),
('Simone','Kalisch','skalisch2n@privacy.gov.au',20.75),
('Fernande','Vallack','fvallack2o@i2i.jp',84.25),
('Benoit','Westbury','bwestbury2p@creativecommons.org',26.0),
('Vania','Farncombe','vfarncombe2q@businesswire.com',28.5),
('Keenan','Le Floch','klefloch2r@salon.com',41.25),
('Tonie','Waycot','twaycot2s@reference.com',49.5),
('Alissa','Alfonsetto','aalfonsetto2t@purevolume.com',43.0),
('Kaylil','Tomes','ktomes2u@hatena.ne.jp',23.5),
('Hubert','Filipic','hfilipic2v@sciencedirect.com',70.5),
('Meredith','Lanmeid','mlanmeid2w@paginegialle.it',20.25),
('Carlin','Ludy','cludy2x@vkontakte.ru',7.0),
('Dorian','Francesc','dfrancesc2y@creativecommons.org',71.5),
('Minerva','Raylton','mraylton2z@blogs.com',58.5),
('Vick','Samms','vsamms30@jigsy.com',78.0),
('Doug','Fullalove','dfullalove31@baidu.com',46.5),
('Arte','Emilien','aemilien32@freewebs.com',45.5),
('Niki','Roskrug','nroskrug33@google.pl',0.0),
('Lorilyn','Good','lgood34@ihg.com',95.0),
('Tova','Labro','tlabro35@behance.net',68.0),
('Cathe','Laimable','claimable36@yelp.com',0.75),
('Rianon','Sausman','rsausman37@networksolutions.com',85.25),
('Barbabra','Bonfield','bbonfield38@ca.gov',71.75),
('Juline','Yakutin','jyakutin39@sakura.ne.jp',11.75),
('Agatha','Gasnell','agasnell3a@mozilla.com',99.5),
('Jillian','Mushet','jmushet3b@blogspot.com',95.0),
('Myrtice','Andrys','mandrys3c@stanford.edu',82.5),
('Shellysheldon','Torrans','storrans3d@bluehost.com',19.75),
('Almeria','Girardey','agirardey3e@arizona.edu',1.75),
('Putnem','Bartelli','pbartelli3f@purevolume.com',21.5),
('Laureen','Rutland','lrutland3g@i2i.jp',33.25),
('Kirbie','Goodding','kgoodding3h@simplemachines.org',32.75),
('Elianora','Godden','egodden3i@cdc.gov',28.25),
('Celia','Cattlow','ccattlow3j@alibaba.com',22.0),
('Natty','Gircke','ngircke3k@google.de',65.5),
('Alix','Nichol','anichol3l@hatena.ne.jp',50.0),
('Robyn','Overall','roverall3m@bbb.org',59.0),
('Bern','Minihan','bminihan3n@sourceforge.net',53.75),
('Tilly','Ritchie','tritchie3o@is.gd',55.75),
('Pegeen','Dalinder','pdalinder3p@smugmug.com',10.25),
('Guglielmo','Sewter','gsewter3q@instagram.com',18.75),
('Ellerey','Mapletoft','emapletoft3r@gmpg.org',57.0),
('Nelia','Stangroom','nstangroom3s@usa.gov',48.5),
('Germayne','Shephard','gshephard3t@domainmarket.com',1.25),
('Codie','Pinner','cpinner3u@godaddy.com',33.75),
('Haskel','Jennaroy','hjennaroy3v@jigsy.com',89.25),
('Ofilia','Briscam','obriscam3w@bloglines.com',89.75),
('Parry','Meechan','pmeechan3x@discovery.com',95.0),
('Almira','Mc Dermid','amcdermid3y@lycos.com',86.25),
('Josi','Pinnock','jpinnock3z@paginegialle.it',34.75),
('Ravi','Mustchin','rmustchin40@nydailynews.com',76.0),
('Winnie','Ahmad','wahmad41@odnoklassniki.ru',62.25),
('Corey','Cornil','ccornil42@tripod.com',16.75),
('Zachary','Pabel','zpabel43@admin.ch',76.5),
('Lissy','Kintish','lkintish44@bigcartel.com',66.25),
('Krista','Skelly','kskelly45@pbs.org',4.5),
('Jody','Betteriss','jbetteriss46@example.com',52.75),
('Nalani','Saylor','nsaylor47@ihg.com',3.5),
('Kirsten','Kerkham','kkerkham48@ifeng.com',63.0),
('Ulric','Nuss','unuss49@engadget.com',20.5),
('Rolfe','Oldfield','roldfield4a@photobucket.com',10.25),
('Karlens','Facher','kfacher4b@pen.io',59.5),
('Rosabella','Coling','rcoling4c@usa.gov',48.0),
('Jeri','Yeoman','jyeoman4d@ihg.com',45.75),
('Ferris','Armin','farmin4e@weather.com',83.0),
('Alvira','Skerratt','askerratt4f@ted.com',17.75),
('Bunnie','Cawthra','bcawthra4g@topsy.com',52.75),
('Janeen','Hilbourne','jhilbourne4h@eepurl.com',7.75),
('Eyde','Bartunek','ebartunek4i@youtu.be',99.75),
('Jinny','Jouanny','jjouanny4j@w3.org',27.0),
('Conny','Rapps','crapps4k@meetup.com',68.5),
('Fernanda','Shovlar','fshovlar4l@printfriendly.com',24.25),
('Leonanie','Vaudrey','lvaudrey4m@nbcnews.com',34.0),
('Mathian','Maffin','mmaffin4n@godaddy.com',32.0),
('Jamison','Soltan','jsoltan4o@tmall.com',99.75),
('Fredra','Fogt','ffogt4p@eventbrite.com',85.5),
('Geri','Lingard','glingard4q@merriam-webster.com',25.5),
('Meyer','Duckworth','mduckworth4r@symantec.com',21.25),
('Lanae','Crown','lcrown4s@cocolog-nifty.com',25.0),
('Mureil','Weldon','mweldon4t@discuz.net',42.75),
('Price','Zmitrovich','pzmitrovich4u@tripadvisor.com',23.25),
('Kaleb','Glenfield','kglenfield4v@gmpg.org',27.0),
('Piper','Ostick','postick4w@tumblr.com',100.0),
('Sherman','Crosetti','scrosetti4x@ask.com',27.5),
('Beltran','Adlem','badlem4y@howstuffworks.com',67.25),
('Dacy','Sloam','dsloam4z@wikimedia.org',30.75),
('Anet','Reade','areade50@vinaora.com',99.0),
('Julie','Leat','jleat51@arizona.edu',94.5),
('Tamqrah','Maciaszek','tmaciaszek52@soundcloud.com',65.25),
('Madelin','Saltmarshe','msaltmarshe53@apache.org',21.5),
('Ellwood','Sandwich','esandwich54@cnet.com',26.25),
('Jonie','Scarasbrick','jscarasbrick55@last.fm',73.25),
('Karlee','Masdon','kmasdon56@smh.com.au',64.75),
('Meggie','Rohlf','mrohlf57@canalblog.com',5.75),
('Tamra','Connick','tconnick58@ezinearticles.com',48.75),
('Keelby','Matthaus','kmatthaus59@infoseek.co.jp',90.75),
('Ivie','Firidolfi','ifiridolfi5a@wired.com',76.25),
('Meyer','Ewers','mewers5b@altervista.org',17.0),
('Adham','Raywood','araywood5c@tinypic.com',92.75),
('De witt','Hanmore','dhanmore5d@cyberchimps.com',5.75),
('Abbie','Magee','amagee5e@nyu.edu',17.75),
('Ursa','Pentercost','upentercost5f@aol.com',75.25),
('Thurston','Corwood','tcorwood5g@tamu.edu',29.0),
('Martino','Boxhall','mboxhall5h@harvard.edu',39.0),
('Bartlet','Whistance','bwhistance5i@biblegateway.com',98.25),
('Cele','Jessen','cjessen5j@123-reg.co.uk',31.5),
('Kellby','Davidov','kdavidov5k@woothemes.com',96.75),
('Sianna','Genny','sgenny5l@bing.com',52.25),
('Bennett','Perin','bperin5m@mozilla.org',72.25),
('Benson','Senner','bsenner5n@moonfruit.com',75.0),
('Vlad','Turban','vturban5o@mayoclinic.com',64.75),
('Sam','Duny','sduny5p@imageshack.us',94.0),
('Candice','Flipek','cflipek5q@nymag.com',13.25),
('Antonie','Sudy','asudy5r@spiegel.de',25.0),
('Cyrillus','Clutton','cclutton5s@cnet.com',46.0),
('Beau','Beardsworth','bbeardsworth5t@digg.com',7.25),
('Preston','Renzullo','prenzullo5u@webnode.com',40.25),
('Bette','Josefsson','bjosefsson5v@reverbnation.com',23.5),
('Hasty','Abramsky','habramsky5w@cbsnews.com',17.75),
('Birch','Pipping','bpipping5x@bing.com',3.5),
('Alicia','Borland','aborland5y@zimbio.com',86.0),
('Rozanna','Voas','rvoas5z@w3.org',0.75),
('Danette','Betjeman','dbetjeman60@home.pl',97.75),
('Dermot','Gilhool','dgilhool61@gnu.org',93.25),
('Margie','MacAdie','mmacadie62@usnews.com',70.0),
('Celina','Fendlen','cfendlen63@cdbaby.com',78.25),
('Kelley','Leinster','kleinster64@pcworld.com',25.75),
('Faye','Raggitt','fraggitt65@wordpress.com',52.75),
('Isidro','Weafer','iweafer66@constantcontact.com',79.75),
('Vallie','Sausman','vsausman67@businessweek.com',16.0),
('Burr','Mithan','bmithan68@pinterest.com',23.25),
('Myrah','Gniewosz','mgniewosz69@wordpress.com',51.0),
('Arlee','Osanne','aosanne6a@dagondesign.com',97.25),
('Giacinta','Saffon','gsaffon6b@photobucket.com',43.5),
('Vanda','Squirrel','vsquirrel6c@ning.com',67.25),
('Emyle','Leon','eleon6d@tinyurl.com',75.0),
('Iosep','Offiler','ioffiler6e@cbsnews.com',9.25),
('Alex','Longcaster','alongcaster6f@ow.ly',32.0),
('Aksel','Pattini','apattini6g@posterous.com',4.5),
('Dore','Bugden','dbugden6h@shutterfly.com',25.25),
('Althea','Toupe','atoupe6i@w3.org',34.75),
('Mycah','Kumar','mkumar6j@omniture.com',26.0),
('Bruis','Sommers','bsommers6k@chron.com',14.0),
('Vittoria','Brown','vbrown6l@wufoo.com',71.5),
('Alys','Polley','apolley6m@liveinternet.ru',66.25),
('Bonita','Bebbell','bbebbell6n@uiuc.edu',59.5),
('Rowney','Dobing','rdobing6o@noaa.gov',73.75),
('Ameline','McKeag','amckeag6p@digg.com',51.75),
('Glyn','Lartice','glartice6q@joomla.org',5.25),
('Brana','Chicotti','bchicotti6r@soup.io',28.5),
('Mikey','Roscow','mroscow6s@nytimes.com',11.25),
('Boot','Jobbins','bjobbins6t@cocolog-nifty.com',30.5),
('Shaun','Holsall','sholsall6u@hhs.gov',41.25),
('Humfrey','Buick','hbuick6v@chron.com',23.25),
('Parker','McGilvra','pmcgilvra6w@wp.com',34.0),
('Wait','Sunley','wsunley6x@phpbb.com',62.25),
('Elora','Cousens','ecousens6y@infoseek.co.jp',10.0),
('Shirline','Kanwell','skanwell6z@sciencedirect.com',48.75),
('Kamilah','Fawdery','kfawdery70@chron.com',64.75),
('Hana','Dehn','hdehn71@biglobe.ne.jp',2.25),
('Mack','Chartman','mchartman72@tiny.cc',49.5),
('Inessa','Segges','isegges73@t.co',71.0),
('Haleigh','Ayris','hayris74@flavors.me',11.75),
('Annabela','Coultar','acoultar75@live.com',17.0),
('Abelard','Heakins','aheakins76@oakley.com',91.5),
('Rosetta','Harwick','rharwick77@timesonline.co.uk',85.5),
('Serge','Shoesmith','sshoesmith78@house.gov',58.5),
('Ilysa','Whellans','iwhellans79@who.int',82.75),
('Ronalda','Keay','rkeay7a@macromedia.com',62.0),
('Ludwig','Togher','ltogher7b@spotify.com',72.75),
('Griffie','Willoway','gwilloway7c@linkedin.com',43.25),
('Nikolos','Conti','nconti7d@wired.com',32.5),
('Clemence','Enrico','cenrico7e@virginia.edu',99.75),
('Vina','Fenge','vfenge7f@blogspot.com',32.25),
('Jobyna','Hutchinson','jhutchinson7g@chicagotribune.com',38.0),
('Raffaello','Durrans','rdurrans7h@rambler.ru',95.5),
('Axe','Kellick','akellick7i@live.com',29.25),
('Claybourne','Worman','cworman7j@state.gov',69.25),
('Aksel','Letts','aletts7k@yelp.com',83.5),
('Nowell','Desaur','ndesaur7l@ed.gov',33.25),
('Erin','Tubritt','etubritt7m@yahoo.co.jp',25.75),
('Conni','Dickens','cdickens7n@yandex.ru',43.75),
('Matilde','Semour','msemour7o@cocolog-nifty.com',54.5),
('Nobe','Bolle','nbolle7p@nih.gov',24.0),
('Konrad','Vigours','kvigours7q@discovery.com',23.25),
('Felice','Hover','fhover7r@soundcloud.com',35.75),
('Gav','Latan','glatan7s@diigo.com',28.75),
('Blinnie','Lerwill','blerwill7t@npr.org',49.5),
('Lalo','Oldknowe','loldknowe7u@oaic.gov.au',83.5),
('Babita','McVee','bmcvee7v@linkedin.com',48.75),
('Kirby','Widdecombe','kwiddecombe7w@europa.eu',15.5),
('Chadwick','Ranshaw','cranshaw7x@msn.com',96.0),
('Vlad','Deehan','vdeehan7y@desdev.cn',82.75),
('Ilsa','Teligin','iteligin7z@angelfire.com',73.0),
('Hailey','Sloane','hsloane80@mysql.com',71.25),
('Zonnya','Limbert','zlimbert81@pen.io',65.5),
('Cazzie','Adshead','cadshead82@constantcontact.com',41.75),
('Ellissa','Geerling','egeerling83@aol.com',96.0),
('Bride','Molesworth','bmolesworth84@desdev.cn',36.0),
('Luella','Pepys','lpepys85@ycombinator.com',9.75),
('Cassandre','Orae','corae86@mapy.cz',26.0),
('Jake','Sanbrooke','jsanbrooke87@google.com.br',78.0),
('Karleen','Alner','kalner88@narod.ru',0.75),
('Teodorico','Pryce','tpryce89@taobao.com',76.0),
('Shermie','Balsillie','sbalsillie8a@ftc.gov',45.5),
('Keith','Reen','kreen8b@msn.com',89.5),
('Maiga','Flounders','mflounders8c@google.com.au',99.25),
('Karl','Biddulph','kbiddulph8d@joomla.org',74.25),
('Giusto','Barensky','gbarensky8e@samsung.com',38.75),
('Loren','Webster','lwebster8f@privacy.gov.au',18.5),
('Belvia','Clyne','bclyne8g@microsoft.com',18.75),
('Janelle','Cobelli','jcobelli8h@livejournal.com',42.0),
('Mac','Burd','mburd8i@tumblr.com',91.75),
('Klaus','Cattonnet','kcattonnet8j@reuters.com',28.25),
('Ruperto','Cafferky','rcafferky8k@hugedomains.com',76.25),
('Benton','Grosier','bgrosier8l@epa.gov',30.5),
('Melesa','Serridge','mserridge8m@1688.com',86.75),
('Brit','Williamson','bwilliamson8n@nih.gov',89.25),
('Tilly','Sellens','tsellens8o@hostgator.com',76.0),
('Jenilee','Ellice','jellice8p@ameblo.jp',77.75),
('Florella','Molyneaux','fmolyneaux8q@nifty.com',26.0),
('Dee','Peasey','dpeasey8r@walmart.com',7.75),
('Ayn','Cristofori','acristofori8s@jiathis.com',22.5),
('Bryon','Tocher','btocher8t@psu.edu',11.0),
('Vera','Sandry','vsandry8u@cloudflare.com',17.25),
('Cleveland','Langan','clangan8v@prnewswire.com',82.5),
('Ilario','Batman','ibatman8w@nytimes.com',57.0),
('Herman','Hubbins','hhubbins8x@army.mil',9.5),
('Vania','Chung','vchung8y@sciencedaily.com',33.0),
('Trent','McGairl','tmcgairl8z@gmpg.org',64.75),
('Chrissy','Craigie','ccraigie90@blinklist.com',70.0),
('Judith','Kik','jkik91@printfriendly.com',34.5),
('Norman','Ganning','nganning92@marriott.com',76.25),
('Monique','Tindall','mtindall93@jiathis.com',64.75),
('Rina','Zylberdik','rzylberdik94@europa.eu',51.75),
('Clementius','Lauthian','clauthian95@51.la',87.25),
('Raynell','Prosch','rprosch96@myspace.com',75.5),
('Lorne','Dallosso','ldallosso97@dailymotion.com',44.75),
('Rodrick','Potkins','rpotkins98@merriam-webster.com',82.5),
('Rainer','Pottinger','rpottinger99@woothemes.com',10.0),
('Redd','Speeks','rspeeks9a@goo.ne.jp',87.0),
('Roberto','Pauletti','rpauletti9b@istockphoto.com',51.75),
('Horton','Stag','hstag9c@shutterfly.com',92.0),
('Dallas','Rawstron','drawstron9d@privacy.gov.au',53.0),
('Joella','Elton','jelton9e@tiny.cc',3.75),
('Hal','Plaice','hplaice9f@macromedia.com',79.0),
('Cammy','Selby','cselby9g@behance.net',56.0),
('Regina','Ellin','rellin9h@liveinternet.ru',71.5),
('Rudolph','Smalman','rsmalman9i@dedecms.com',59.25),
('Sallee','Slayny','sslayny9j@vimeo.com',22.5),
('Mirabelle','Connaughton','mconnaughton9k@woothemes.com',30.0),
('Fran','Gapper','fgapper9l@omniture.com',28.25),
('Kasper','Rayer','krayer9m@about.com',31.75),
('Lida','Petherick','lpetherick9n@house.gov',55.5),
('Heloise','Ventham','hventham9o@rambler.ru',71.0),
('Humberto','Koop','hkoop9p@wufoo.com',1.0),
('Margarette','Dudenie','mdudenie9q@sohu.com',24.75),
('Dominique','Rorke','drorke9r@rediff.com',80.25),
('Donovan','Tonry','dtonry9s@cnet.com',14.75),
('Gustie','Servant','gservant9t@1688.com',40.0),
('Gaspard','Darnborough','gdarnborough9u@surveymonkey.com',33.5),
('Silvano','Ronisch','sronisch9v@pagesperso-orange.fr',20.25),
('Wanda','Lammertz','wlammertz9w@123-reg.co.uk',25.75),
('Marylin','Lush','mlush9x@nifty.com',59.75),
('Harriett','Van der Son','hvanderson9y@tripod.com',99.5),
('Jorge','Daine','jdaine9z@pbs.org',8.0),
('Cassie','Dowdall','cdowdalla0@bbb.org',2.5),
('Pavel','Treneer','ptreneera1@army.mil',63.75),
('Ranice','Eydel','reydela2@facebook.com',84.5),
('Anton','MacSherry','amacsherrya3@seesaa.net',12.0),
('Sergei','Stidworthy','sstidworthya4@topsy.com',81.0),
('Romonda','Nagle','rnaglea5@linkedin.com',72.5),
('Reggi','Drowsfield','rdrowsfielda6@a8.net',94.0),
('Brear','Fley','bfleya7@sitemeter.com',2.0),
('Ernest','Ockleshaw','eockleshawa8@tripadvisor.com',81.0),
('Franciskus','Remington','fremingtona9@ebay.co.uk',97.5),
('Marven','Callear','mcallearaa@sciencedaily.com',58.25),
('Corbett','Dymock','cdymockab@whitehouse.gov',58.5),
('Jeddy','Arrigucci','jarrigucciac@gmpg.org',18.0),
('Kittie','Loughnan','kloughnanad@amazon.co.uk',78.25),
('Reinaldo','Pendle','rpendleae@constantcontact.com',93.5),
('Aloise','Welfare','awelfareaf@unesco.org',27.5),
('Isaiah','Maciocia','imaciociaag@fema.gov',92.0),
('Dayle','Massei','dmasseiah@ow.ly',49.5),
('Brennen','Mulrenan','bmulrenanai@multiply.com',6.25),
('Rozella','Courtman','rcourtmanaj@sfgate.com',56.25),
('Mirilla','Guthrum','mguthrumak@taobao.com',72.5),
('Zackariah','Rex','zrexal@vimeo.com',60.25),
('Blinny','Keepin','bkeepinam@is.gd',2.25),
('Tierney','Crosher','tcrosheran@qq.com',88.75),
('Brigitte','Koch','bkochao@soundcloud.com',69.25),
('Barny','Baumadier','bbaumadierap@cafepress.com',12.25),
('Ali','Passman','apassmanaq@sina.com.cn',69.75),
('Meyer','Foxworthy','mfoxworthyar@github.com',66.25),
('Gerri','Orry','gorryas@dyndns.org',23.75),
('Niels','Pellamont','npellamontat@hp.com',36.5),
('Florinda','Vellden','fvelldenau@cocolog-nifty.com',7.75),
('Walliw','Hilley','whilleyav@wired.com',17.0),
('York','Heatley','yheatleyaw@marriott.com',29.0),
('Teodorico','Danford','tdanfordax@netscape.com',22.0),
('Barth','Barnett','bbarnettay@imageshack.us',70.75),
('Karoly','Baysting','kbaystingaz@artisteer.com',23.25),
('Florie','Cattonnet','fcattonnetb0@zdnet.com',46.75),
('Thaxter','Battersby','tbattersbyb1@opera.com',43.75),
('Valida','Kibble','vkibbleb2@wordpress.com',37.25),
('Agnola','McMurray','amcmurrayb3@nyu.edu',3.5),
('Thacher','Caws','tcawsb4@tripadvisor.com',97.5),
('Koralle','Fronks','kfronksb5@sina.com.cn',42.0),
('Dru','Roome','droomeb6@npr.org',17.5),
('Dukie','Cottel','dcottelb7@free.fr',27.0),
('Shanie','Kleinert','skleinertb8@un.org',32.75),
('Brit','Jobb','bjobbb9@rediff.com',17.5),
('Lauritz','McBeth','lmcbethba@dyndns.org',4.0),
('Winnah','Eldered','welderedbb@spiegel.de',73.0),
('Luce','Tapin','ltapinbc@nih.gov',39.75),
('Shellysheldon','O''Fearguise','sofearguisebd@nifty.com',96.75),
('Ruthi','Lemar','rlemarbe@shareasale.com',35.5),
('Aubine','Mosson','amossonbf@redcross.org',19.0),
('Lothaire','Goldney','lgoldneybg@storify.com',29.5),
('Bastien','Snipe','bsnipebh@si.edu',14.5),
('Ebonee','Boxe','eboxebi@gravatar.com',66.5),
('John','Frodsham','jfrodshambj@eepurl.com',97.75),
('Welbie','Bartolomieu','wbartolomieubk@marriott.com',68.75),
('Fedora','Sellner','fsellnerbl@webmd.com',24.0),
('Flore','Cleland','fclelandbm@last.fm',14.75),
('Bron','Risen','brisenbn@pcworld.com',49.75),
('Lemmy','Blanchflower','lblanchflowerbo@home.pl',89.0),
('Wilma','Tireman','wtiremanbp@nyu.edu',48.5),
('Freemon','Bartrap','fbartrapbq@goo.gl',60.25),
('Iorgos','Mossdale','imossdalebr@upenn.edu',66.5),
('Rowena','Gabriel','rgabrielbs@google.de',35.25),
('Ellette','Giovannetti','egiovannettibt@seesaa.net',12.5),
('Hailey','Shaves','hshavesbu@mail.ru',41.0),
('Shellie','Cahen','scahenbv@feedburner.com',47.25),
('Katherina','Vasiljevic','kvasiljevicbw@fc2.com',37.75),
('Xena','Grolmann','xgrolmannbx@twitpic.com',53.75),
('Umeko','Robertazzi','urobertazziby@symantec.com',16.5),
('Doe','Gerardi','dgerardibz@pagesperso-orange.fr',64.25),
('Ive','Szabo','iszaboc0@buzzfeed.com',75.75),
('Tally','Diehn','tdiehnc1@msu.edu',65.0),
('Elva','Bye','ebyec2@toplist.cz',42.0),
('Rafaellle','Dumelow','rdumelowc3@furl.net',69.25),
('Liz','Aveling','lavelingc4@europa.eu',36.5),
('Jackelyn','Gerasch','jgeraschc5@rediff.com',51.25),
('Daisey','Titcomb','dtitcombc6@narod.ru',45.0),
('Edna','Nannoni','enannonic7@statcounter.com',87.0),
('Richart','Abbis','rabbisc8@ucoz.ru',88.25),
('Bevvy','Ellwand','bellwandc9@mayoclinic.com',5.75),
('Jae','Roalfe','jroalfeca@slate.com',91.75),
('Steven','Burstowe','sburstowecb@si.edu',90.25),
('Dewie','Giberd','dgiberdcc@sun.com',74.25),
('Abran','Caren','acarencd@utexas.edu',27.0),
('Teriann','Werrit','twerritce@nifty.com',7.75),
('Delphinia','Sauniere','dsaunierecf@t-online.de',85.75),
('Shelby','Deegan','sdeegancg@bluehost.com',73.0),
('Jerrylee','Luttger','jluttgerch@bbc.co.uk',22.0),
('Bettine','Consterdine','bconsterdineci@hostgator.com',55.5),
('Mariellen','Franz','mfranzcj@goo.gl',33.75),
('Minetta','Korb','mkorbck@list-manage.com',11.25),
('Melly','MacCart','mmaccartcl@amazon.co.jp',25.25),
('Rubie','Comi','rcomicm@yahoo.co.jp',53.5),
('Kristin','Tomaszek','ktomaszekcn@npr.org',70.5),
('Derk','Fallis','dfallisco@cnn.com',17.75),
('Madelyn','Pickless','mpicklesscp@who.int',7.25),
('Shannah','Dursley','sdursleycq@guardian.co.uk',13.25),
('Maritsa','Eymor','meymorcr@baidu.com',79.75),
('Josee','Shambrooke','jshambrookecs@google.nl',81.25),
('Aline','Cheeney','acheeneyct@parallels.com',31.5),
('Adora','Kryszka','akryszkacu@booking.com',32.5),
('Bunni','Malkinson','bmalkinsoncv@a8.net',50.0),
('Brose','Luciano','blucianocw@google.cn',69.25),
('Saloma','Cromack','scromackcx@acquirethisname.com',4.25),
('Borg','Bletcher','bbletchercy@bravesites.com',63.5),
('Dominga','Lightwood','dlightwoodcz@omniture.com',41.5),
('Markos','Cutcliffe','mcutcliffed0@irs.gov',99.5),
('Hedvig','Thorington','hthoringtond1@youtu.be',63.0),
('Leilah','Tonkinson','ltonkinsond2@photobucket.com',12.0),
('Aldis','Mead','ameadd3@amazon.co.jp',40.5),
('Marcy','Sunock','msunockd4@woothemes.com',80.25),
('Nata','Sowerby','nsowerbyd5@adobe.com',87.75),
('Hamil','Clevely','hclevelyd6@sphinn.com',43.75),
('Jesselyn','Loveland','jlovelandd7@baidu.com',13.25),
('Sib','Matzaitis','smatzaitisd8@businessinsider.com',13.75),
('Howie','Leile','hleiled9@pbs.org',82.0),
('Debby','Comelini','dcomelinida@dell.com',40.5),
('Syd','Tydeman','stydemandb@taobao.com',99.75),
('Marcus','Dallaway','mdallawaydc@google.de',53.75),
('Rochella','Paulet','rpauletdd@xrea.com',97.5),
('Dee dee','Klisch','dklischde@dot.gov',61.0),
('Gage','Drewson','gdrewsondf@sogou.com',87.5),
('Roberto','Harden','rhardendg@bloglines.com',67.5),
('Leonelle','Delacourt','ldelacourtdh@fc2.com',27.5),
('Alexia','Hansard','ahansarddi@dagondesign.com',0.25),
('Nick','Tregunna','ntregunnadj@printfriendly.com',14.0),
('Koenraad','Fearick','kfearickdk@amazonaws.com',63.25),
('Thia','Cockley','tcockleydl@bloomberg.com',66.5),
('Iorgos','Hamsher','ihamsherdm@tiny.cc',24.75),
('Diane','Nesey','dneseydn@webeden.co.uk',11.5),
('Xaviera','Flockhart','xflockhartdo@soundcloud.com',52.25),
('Issiah','Loughton','iloughtondp@yahoo.com',14.5),
('Benny','Oblein','bobleindq@webnode.com',69.25),
('Camel','Girodier','cgirodierdr@archive.org',8.75),
('Courtnay','Mallinson','cmallinsonds@hostgator.com',49.75),
('Orsa','Iannini','oianninidt@multiply.com',99.25),
('Darnell','Shearme','dshearmedu@opensource.org',55.5),
('Juanita','Bosdet','jbosdetdv@mapquest.com',48.5),
('Oren','Van Rembrandt','ovanrembrandtdw@e-recht24.de',91.25),
('Nickola','Treslove','ntreslovedx@lycos.com',62.75),
('Joann','Probat','jprobatdy@amazonaws.com',90.0),
('Camala','Britto','cbrittodz@jiathis.com',88.75),
('Maggy','Wherrett','mwherrette0@usatoday.com',100.0),
('Lou','Shorto','lshortoe1@walmart.com',26.25),
('Marsiella','Brafferton','mbraffertone2@cdbaby.com',75.25),
('Aloisia','Cockayme','acockaymee3@earthlink.net',14.25),
('Alphard','Suston','asustone4@usgs.gov',65.25),
('Kimmi','Costock','kcostocke5@sina.com.cn',27.25),
('Rhody','Warrington','rwarringtone6@wix.com',21.0),
('Rubia','O'' Ronan','roronane7@livejournal.com',29.25),
('Lacy','Stanlake','lstanlakee8@uiuc.edu',59.25),
('Eward','Hadfield','ehadfielde9@histats.com',94.75),
('Norah','Greggersen','ngreggersenea@yellowbook.com',41.5),
('Kori','Ragsdall','kragsdalleb@columbia.edu',69.5),
('Danna','Rowsell','drowsellec@cnn.com',81.25),
('Caprice','Wyles','cwylesed@fema.gov',87.75),
('Antons','Polo','apoloee@g.co',36.5),
('Llewellyn','Koeppe','lkoeppeef@businessinsider.com',66.25),
('Angeline','Riddick','ariddickeg@dailymail.co.uk',56.0),
('Guy','Macellar','gmacellareh@abc.net.au',52.25),
('Marshal','Ciottoi','mciottoiei@utexas.edu',91.75),
('Audre','Blenkinsopp','ablenkinsoppej@home.pl',67.0),
('Chas','Whitnell','cwhitnellek@va.gov',42.25),
('Gwendolen','Witcombe','gwitcombeel@rakuten.co.jp',74.5),
('Horacio','Prangle','hprangleem@buzzfeed.com',54.5),
('Ganny','Vella','gvellaen@privacy.gov.au',84.25),
('Keene','Pengilley','kpengilleyeo@symantec.com',14.5),
('Vonny','Jersch','vjerschep@twitpic.com',17.25),
('Anne','Boanas','aboanaseq@mtv.com',13.25),
('Briant','Dulinty','bdulintyer@china.com.cn',14.25),
('Barbee','Cano','bcanoes@youtu.be',95.75),
('Magdalena','Waterstone','mwaterstoneet@angelfire.com',2.5),
('Ninetta','Queree','nquereeeu@mac.com',14.75),
('Jessika','Labell','jlabellev@geocities.com',59.0),
('Max','Asbury','masburyew@phpbb.com',38.75),
('Dorothy','Deyes','ddeyesex@csmonitor.com',12.5),
('Moise','Greet','mgreetey@patch.com',74.75),
('Farlee','Maes','fmaesez@dell.com',0.5),
('Anthiathia','Eilhermann','aeilhermannf0@mlb.com',60.75),
('Karlie','Deer','kdeerf1@sohu.com',92.75),
('Jaimie','Smorfit','jsmorfitf2@dedecms.com',58.25),
('Zollie','Stansfield','zstansfieldf3@buzzfeed.com',62.0),
('Christie','Chopy','cchopyf4@flickr.com',97.5),
('Sonia','Coen','scoenf5@vk.com',21.0),
('Dorie','Balhatchet','dbalhatchetf6@netscape.com',72.25),
('Joanne','Mcwhinnie','jmcwhinnief7@adobe.com',52.75),
('Lotta','Mickleborough','lmickleboroughf8@unicef.org',58.0),
('Templeton','Decker','tdeckerf9@sina.com.cn',93.5),
('Harriett','Ribbon','hribbonfa@cbc.ca',55.75),
('Joyous','Mushart','jmushartfb@youtube.com',74.0),
('Gloria','Beccles','gbecclesfc@smugmug.com',93.25),
('Cullen','Jaze','cjazefd@ask.com',39.75),
('Craig','Isaacson','cisaacsonfe@com.com',94.25),
('Sydelle','Peck','speckff@example.com',71.25),
('Jocko','Tideswell','jtideswellfg@home.pl',31.75),
('Rosalynd','Frizell','rfrizellfh@amazon.de',63.5),
('Obadiah','Sykes','osykesfi@oracle.com',3.75),
('Dedra','Pottberry','dpottberryfj@jalbum.net',92.5),
('Grissel','Labin','glabinfk@mtv.com',37.5),
('Carling','Seman','csemanfl@delicious.com',92.0),
('Skipp','Haggar','shaggarfm@intel.com',12.25),
('Ronda','Valeri','rvalerifn@upenn.edu',75.0),
('Kit','Anderson','kandersonfo@miibeian.gov.cn',74.25),
('Cirstoforo','Coey','ccoeyfp@eventbrite.com',78.25),
('Annmarie','Maynell','amaynellfq@berkeley.edu',20.5),
('Milena','Mylan','mmylanfr@amazon.co.jp',42.75),
('Bennie','Lackner','blacknerfs@wp.com',23.25),
('Packston','Drew-Clifton','pdrewcliftonft@taobao.com',12.5),
('Moritz','Stanlock','mstanlockfu@sakura.ne.jp',78.0),
('Kayle','Gilman','kgilmanfv@addtoany.com',97.5),
('Leeland','Crenage','lcrenagefw@ucoz.ru',66.0),
('Kylila','Jacobsz','kjacobszfx@state.gov',42.0),
('Ollie','Kellart','okellartfy@ibm.com',95.0),
('Tamara','Haack','thaackfz@imgur.com',93.75),
('Harri','Spacie','hspacieg0@google.co.jp',50.0),
('Bernie','Somerton','bsomertong1@hhs.gov',8.25),
('Robbie','Sharvell','rsharvellg2@quantcast.com',17.0),
('Carmina','Horsburgh','chorsburghg3@google.co.uk',24.25),
('Emelda','Lawman','elawmang4@wordpress.com',95.75),
('Crissy','Rosencrantz','crosencrantzg5@sphinn.com',52.0),
('Deeanne','Slimming','dslimmingg6@google.com.au',7.0),
('Cesya','Imore','cimoreg7@smh.com.au',38.5),
('Wynn','Iacivelli','wiacivellig8@studiopress.com',49.75),
('Gussy','Hamfleet','ghamfleetg9@weather.com',48.5),
('Adore','Pittham','apitthamga@miitbeian.gov.cn',73.75),
('Rae','Brearley','rbrearleygb@csmonitor.com',75.5),
('Humphrey','Edy','hedygc@i2i.jp',27.5),
('Tudor','Tincombe','ttincombegd@t-online.de',8.75),
('Nonnah','Storrock','nstorrockge@dyndns.org',55.75),
('Margit','Primrose','mprimrosegf@php.net',7.5),
('Tanitansy','Van den Velden','tvandenveldengg@foxnews.com',71.75),
('Reagan','Estevez','restevezgh@dyndns.org',0.75),
('Mal','McCandless','mmccandlessgi@pcworld.com',30.0),
('Gaylor','Skilling','gskillinggj@globo.com',24.5),
('Wilfred','Webby','wwebbygk@sogou.com',69.0),
('Arel','Saltmarshe','asaltmarshegl@google.com',42.5),
('Ronni','Lodin','rlodingm@jugem.jp',43.25),
('Birdie','Steers','bsteersgn@mapquest.com',62.25),
('Devlin','Collyear','dcollyeargo@hugedomains.com',51.75),
('Shalne','Caslett','scaslettgp@fda.gov',11.5),
('Alyssa','McKenna','amckennagq@ed.gov',34.0),
('Mord','Websdale','mwebsdalegr@indiegogo.com',53.5),
('Al','Cheese','acheesegs@ovh.net',71.25),
('Allsun','Taylour','ataylourgt@liveinternet.ru',15.0),
('Isidora','Simone','isimonegu@csmonitor.com',29.0),
('Juana','Bulfit','jbulfitgv@stanford.edu',0.5),
('Etheline','D''Ambrosi','edambrosigw@nyu.edu',54.5),
('Blondelle','McPhelimey','bmcphelimeygx@ftc.gov',15.75),
('Shaun','Tubb','stubbgy@answers.com',34.25),
('Lindsey','Kingman','lkingmangz@admin.ch',26.25),
('Normy','Meffin','nmeffinh0@loc.gov',74.75),
('Ellsworth','Baines','ebainesh1@bing.com',36.25),
('Josepha','Charlewood','jcharlewoodh2@livejournal.com',16.0),
('Base','Bentame','bbentameh3@nymag.com',13.0),
('Kenny','Cowle','kcowleh4@home.pl',33.25),
('Ava','Heninghem','aheninghemh5@pcworld.com',73.75),
('Hana','Braisher','hbraisherh6@ed.gov',7.25),
('Alvin','Brayfield','abrayfieldh7@scribd.com',58.75),
('Norah','Olsson','nolssonh8@unblog.fr',33.25),
('Sibilla','Aikett','saiketth9@trellian.com',37.75),
('Hi','Aleavy','haleavyha@tumblr.com',3.75),
('Riley','Adamowitz','radamowitzhb@dion.ne.jp',69.75),
('Laney','McAmish','lmcamishhc@hubpages.com',97.5),
('Torrin','Schoular','tschoularhd@linkedin.com',32.5),
('Belvia','Sperry','bsperryhe@altervista.org',48.75),
('Timothea','Benkhe','tbenkhehf@foxnews.com',74.5),
('Tilly','Thomsson','tthomssonhg@delicious.com',7.5),
('Trip','Dirr','tdirrhh@simplemachines.org',69.25),
('Ellery','Taborre','etaborrehi@dot.gov',15.5),
('Lynett','Lummus','llummushj@simplemachines.org',99.75),
('Brewer','Peatman','bpeatmanhk@sbwire.com',53.75),
('Lorenza','Atwool','latwoolhl@xing.com',32.0),
('Ignacio','Dunne','idunnehm@sakura.ne.jp',64.25),
('Noemi','Johananov','njohananovhn@loc.gov',68.0),
('Liesa','Chaulk','lchaulkho@google.com.br',98.0),
('Stella','Glancy','sglancyhp@netscape.com',91.5),
('Orren','Avramchik','oavramchikhq@webnode.com',87.25),
('Hazel','Picken','hpickenhr@whitehouse.gov',84.0),
('Jocelyne','Pinhorn','jpinhornhs@youtube.com',30.75),
('Arden','Januszkiewicz','ajanuszkiewiczht@dropbox.com',40.0),
('Roch','Bellsham','rbellshamhu@loc.gov',19.25),
('Leslie','Mauvin','lmauvinhv@cloudflare.com',3.0),
('Egon','Roskell','eroskellhw@wufoo.com',98.0),
('Dot','Greatex','dgreatexhx@arizona.edu',11.5),
('Ky','Stitch','kstitchhy@github.com',25.75),
('Conni','Canizares','ccanizareshz@slashdot.org',76.25),
('Tamar','Pogue','tpoguei0@forbes.com',49.0),
('Terrance','Westhoff','twesthoffi1@smh.com.au',68.0),
('Arnold','Miskimmon','amiskimmoni2@prnewswire.com',33.0),
('Rog','Espinas','respinasi3@jugem.jp',37.25),
('Adolf','Speakman','aspeakmani4@abc.net.au',46.75),
('Early','Idney','eidneyi5@friendfeed.com',2.75),
('Olivero','Delacoste','odelacostei6@ucoz.ru',54.75),
('Gottfried','Scotson','gscotsoni7@nydailynews.com',98.25),
('Holly-anne','O'' Brian','hobriani8@webeden.co.uk',34.0),
('Dagny','Greenslade','dgreensladei9@disqus.com',89.0),
('Catlaina','Rittmeyer','crittmeyeria@uiuc.edu',63.25),
('Loreen','Abramin','labraminib@aol.com',95.75),
('Cece','Jaggi','cjaggiic@examiner.com',91.25),
('Tallulah','Heasly','theaslyid@wix.com',36.75),
('Homerus','Knolles-Green','hknollesgreenie@si.edu',46.5),
('Pyotr','Boggis','pboggisif@eepurl.com',91.5),
('Ellis','Lanegran','elanegranig@vistaprint.com',83.75),
('Marisa','Klempke','mklempkeih@bbb.org',76.75),
('Dannye','Orae','doraeii@upenn.edu',18.25),
('Helenelizabeth','Mannion','hmannionij@pbs.org',91.75),
('Zackariah','Curry','zcurryik@reverbnation.com',57.75),
('Thatcher','Spadaro','tspadaroil@cbc.ca',22.0),
('Earvin','Chippendale','echippendaleim@globo.com',85.0),
('Ardelia','Labbe','alabbein@cbc.ca',68.75),
('Pernell','Sturm','psturmio@goodreads.com',55.0),
('Trenton','Sinson','tsinsonip@gizmodo.com',20.25),
('Romeo','Albert','ralbertiq@webnode.com',52.25),
('Corny','Menlow','cmenlowir@cisco.com',52.0),
('Daryle','O''Kelly','dokellyis@google.it',46.5),
('Garland','Craze','gcrazeit@surveymonkey.com',27.75),
('Troy','Dolle','tdolleiu@bizjournals.com',37.75),
('Toby','Kelso','tkelsoiv@cdbaby.com',96.75),
('Kesley','Honywill','khonywilliw@mlb.com',30.75),
('Dodi','Monahan','dmonahanix@freewebs.com',55.25),
('Gradey','Doy','gdoyiy@google.it',98.0),
('Chaddie','Beer','cbeeriz@addthis.com',54.75),
('Danila','Le Sieur','dlesieurj0@github.com',45.75),
('Barbaraanne','Dewhurst','bdewhurstj1@statcounter.com',19.25),
('Allissa','Roget','arogetj2@cnn.com',56.25),
('Jarib','Oliveira','joliveiraj3@zimbio.com',94.75),
('Bobbee','Harnell','bharnellj4@sphinn.com',90.0),
('Obie','Spurett','ospurettj5@virginia.edu',6.75),
('Robenia','Enderson','rendersonj6@scientificamerican.com',74.25),
('Fiann','Dmisek','fdmisekj7@indiatimes.com',87.75),
('Lindy','Costar','lcostarj8@loc.gov',69.25),
('Abigael','Marriner','amarrinerj9@constantcontact.com',76.5),
('Curr','Formilli','cformillija@ustream.tv',91.5),
('Maddy','Procter','mprocterjb@army.mil',40.25),
('Otho','Gouth','ogouthjc@shinystat.com',28.75),
('Cthrine','Klezmski','cklezmskijd@comcast.net',47.25),
('Fania','Pellington','fpellingtonje@wix.com',89.5),
('Laurie','O''Hannen','lohannenjf@reference.com',69.5),
('Spike','McCoveney','smccoveneyjg@taobao.com',16.0),
('Bree','Fateley','bfateleyjh@nps.gov',26.0),
('Tabbi','Gascard','tgascardji@google.it',82.5),
('Jonas','Denyer','jdenyerjj@hud.gov',70.25),
('Stepha','Gutteridge','sgutteridgejk@a8.net',44.5),
('Rickie','Heckle','rhecklejl@economist.com',25.25),
('Denys','Lippett','dlippettjm@ucoz.com',33.75),
('Ally','Gaddesby','agaddesbyjn@oaic.gov.au',7.75),
('Delainey','Matheson','dmathesonjo@walmart.com',89.75),
('Arel','Fuke','afukejp@ca.gov',23.5),
('Gerrie','Hanshawe','ghanshawejq@redcross.org',67.0),
('Shell','Itzcovichch','sitzcovichchjr@hubpages.com',95.0),
('Karee','Shooter','kshooterjs@youtu.be',97.5),
('Iosep','Pharro','ipharrojt@clickbank.net',23.75),
('Delilah','Goodday','dgooddayju@prlog.org',88.5),
('Emmalee','De Giovanni','edegiovannijv@fema.gov',53.5),
('Kelley','Olyunin','kolyuninjw@fda.gov',15.5),
('Monika','Anker','mankerjx@wired.com',48.75),
('Kirbee','Regglar','kregglarjy@xing.com',7.0),
('Caitrin','Stell','cstelljz@un.org',29.25),
('Noby','Grime','ngrimek0@cisco.com',76.0),
('Christiano','Tregunna','ctregunnak1@sun.com',88.0),
('Shandee','Parsell','sparsellk2@163.com',6.0),
('Mata','Draco','mdracok3@aboutads.info',21.0),
('Patrizius','Hutfield','phutfieldk4@skyrock.com',35.0),
('Christoforo','Cluley','ccluleyk5@mail.ru',93.5),
('Barby','Gosden','bgosdenk6@ft.com',48.25),
('Meir','Smidmoor','msmidmoork7@quantcast.com',54.0),
('Klarika','Fulbrook','kfulbrookk8@berkeley.edu',29.25),
('Garey','Ferenczi','gferenczik9@reference.com',8.0),
('Jackelyn','Swindlehurst','jswindlehurstka@plala.or.jp',73.75),
('Marlowe','Giamo','mgiamokb@arstechnica.com',7.5),
('Hasty','Cerie','hceriekc@soundcloud.com',43.0),
('Thorn','Ruddom','truddomkd@odnoklassniki.ru',42.0),
('Jemima','Reschke','jreschkeke@nationalgeographic.com',9.5),
('Tybie','Bessell','tbessellkf@unesco.org',84.75),
('Pace','Crut','pcrutkg@unblog.fr',88.25),
('Cassey','Babington','cbabingtonkh@europa.eu',95.0),
('Modesty','Holcroft','mholcroftki@ifeng.com',84.0),
('Cassaundra','Gergus','cgerguskj@devhub.com',21.25),
('Katina','Bendik','kbendikkk@netvibes.com',76.5),
('Ado','Earthfield','aearthfieldkl@domainmarket.com',47.0),
('Aloin','Oughton','aoughtonkm@storify.com',72.25),
('Rosalie','Ruppeli','rruppelikn@sfgate.com',54.25),
('Norman','Brisseau','nbrisseauko@shinystat.com',38.5),
('Gilda','Muldrew','gmuldrewkp@imdb.com',6.25),
('Creigh','Walworth','cwalworthkq@cbc.ca',14.25),
('Isabel','Gidney','igidneykr@de.vu',60.5),
('Archambault','Dulling','adullingks@tuttocitta.it',68.0),
('Eustacia','Evreux','eevreuxkt@businessinsider.com',95.75),
('Thea','Christoffe','tchristoffeku@angelfire.com',80.5),
('Cash','Dewhurst','cdewhurstkv@sciencedaily.com',10.5),
('Celestine','Farndale','cfarndalekw@wufoo.com',19.5),
('Blane','Sturley','bsturleykx@google.nl',57.0),
('Radcliffe','Morin','rmorinky@netscape.com',53.25),
('Zahara','McGoldrick','zmcgoldrickkz@nhs.uk',12.25),
('Catherine','Wehden','cwehdenl0@europa.eu',60.25),
('Emmalee','Moen','emoenl1@comsenz.com',91.5),
('Jere','Pinor','jpinorl2@etsy.com',95.5),
('Yettie','Robbey','yrobbeyl3@fc2.com',84.0),
('Rudolph','Wooler','rwoolerl4@pcworld.com',42.75),
('Lennie','Crayden','lcraydenl5@symantec.com',67.25),
('Jamison','Dacks','jdacksl6@github.io',60.5),
('Hattie','Brentnall','hbrentnalll7@china.com.cn',36.25),
('Nilson','Mingard','nmingardl8@theglobeandmail.com',26.75),
('Letitia','Hughland','lhughlandl9@bluehost.com',96.0),
('Twila','Castell','tcastellla@newsvine.com',28.5),
('Arabella','Shuker','ashukerlb@jiathis.com',80.5),
('Dulcea','Asipenko','dasipenkolc@addtoany.com',98.25),
('Billie','Gerren','bgerrenld@dailymail.co.uk',39.0),
('Maddie','Santorini','msantorinile@friendfeed.com',54.5),
('Britta','Sawle','bsawlelf@businessweek.com',47.5),
('Cynthie','Debow','cdebowlg@twitter.com',77.75),
('Rahel','Regis','rregislh@digg.com',10.0),
('Meggy','Timcke','mtimckeli@dion.ne.jp',34.5),
('Harlie','Gable','hgablelj@weebly.com',68.5),
('Dorothy','Rickertsen','drickertsenlk@lycos.com',33.75),
('Emmy','Tincey','etinceyll@china.com.cn',43.25),
('Viole','Bysh','vbyshlm@fotki.com',4.5),
('Myrle','Michelet','mmicheletln@google.it',38.0),
('Si','Scimoni','sscimonilo@biglobe.ne.jp',33.75),
('Chrissie','Skittreal','cskittreallp@newsvine.com',22.25),
('Nicola','Jarnell','njarnelllq@skype.com',97.75),
('Darrell','Kensitt','dkensittlr@hc360.com',98.75),
('Merrile','Delany','mdelanyls@seattletimes.com',29.75),
('Brandy','Awcoate','bawcoatelt@craigslist.org',44.75),
('Nerty','Reagan','nreaganlu@spotify.com',18.25),
('Jesus','Stillwell','jstillwelllv@google.es',47.0),
('Rod','Romao','rromaolw@surveymonkey.com',42.0),
('Adolpho','Novic','anoviclx@imageshack.us',8.0),
('Faunie','Wright','fwrightly@ox.ac.uk',67.25),
('Babbie','Mechem','bmechemlz@cafepress.com',35.0),
('Lilia','Drinkel','ldrinkelm0@google.com.hk',79.0),
('Hi','Clew','hclewm1@examiner.com',82.5),
('Ira','Acheson','iachesonm2@histats.com',10.25),
('Theobald','Alloisi','talloisim3@fotki.com',81.5),
('Brucie','Thirkettle','bthirkettlem4@hexun.com',55.25),
('Dru','Braisted','dbraistedm5@prweb.com',31.0),
('Elton','Cartmer','ecartmerm6@devhub.com',53.5),
('Laurens','Blincowe','lblincowem7@printfriendly.com',61.25),
('Nigel','Lambourn','nlambournm8@jugem.jp',90.0),
('Doralin','Ditty','ddittym9@mlb.com',22.0),
('Patrice','Alstead','palsteadma@usatoday.com',93.0),
('Homere','Trase','htrasemb@goo.gl',50.75),
('Em','Hagwood','ehagwoodmc@linkedin.com',59.5),
('Boy','Dumbleton','bdumbletonmd@g.co',44.5),
('Chiquita','Jollye','cjollyeme@cloudflare.com',16.25),
('Pierrette','Rosenshine','prosenshinemf@jalbum.net',40.0),
('Andre','Bagg','abaggmg@cyberchimps.com',89.5),
('Kerry','Morfey','kmorfeymh@yale.edu',8.5),
('Vincenz','Morstatt','vmorstattmi@smh.com.au',18.75),
('Freida','Varden','fvardenmj@marketwatch.com',99.75),
('Kristopher','Parkman','kparkmanmk@newsvine.com',77.75),
('Antone','Headings','aheadingsml@1688.com',36.25),
('Huntley','Bolsteridge','hbolsteridgemm@dmoz.org',65.75),
('Barris','Clother','bclothermn@yelp.com',24.25),
('Valma','Boner','vbonermo@devhub.com',64.75),
('Enrika','Sikora','esikoramp@aol.com',32.25),
('Bat','Caldeyroux','bcaldeyrouxmq@slideshare.net',90.25),
('Ferne','Ridewood','fridewoodmr@netlog.com',74.0),
('Manya','Tunbridge','mtunbridgems@yellowbook.com',49.25),
('Ivar','Gontier','igontiermt@ustream.tv',67.25),
('Ayn','Gransden','agransdenmu@ifeng.com',37.25),
('Ina','Northrop','inorthropmv@ameblo.jp',99.5),
('Dorthy','ffrench Beytagh','dffrenchbeytaghmw@yahoo.co.jp',54.25),
('Lauree','Roeby','lroebymx@va.gov',50.5),
('Slade','Merwood','smerwoodmy@elegantthemes.com',55.25),
('Brook','Quene','bquenemz@google.ca',40.5),
('Carlita','Waulker','cwaulkern0@friendfeed.com',37.75),
('Daisey','Cadney','dcadneyn1@illinois.edu',31.25),
('Fin','Dennitts','fdennittsn2@mashable.com',83.25),
('Lynda','Ephson','lephsonn3@artisteer.com',71.0),
('Kit','Bunstone','kbunstonen4@addthis.com',89.0),
('Kenton','Powelee','kpoweleen5@w3.org',74.0),
('Wendel','Horder','whordern6@ihg.com',37.5),
('Almeta','Duro','aduron7@cpanel.net',44.75),
('Karee','Huelin','khuelinn8@xing.com',32.75),
('Artair','Ortes','aortesn9@nyu.edu',85.5),
('Neddy','Bartholat','nbartholatna@slideshare.net',97.5),
('Red','Burdge','rburdgenb@bravesites.com',96.75),
('Efren','Brennen','ebrennennc@mit.edu',78.5),
('Mart','Shillingford','mshillingfordnd@yale.edu',97.25),
('Alfie','Klossmann','aklossmannne@goo.ne.jp',13.0),
('Enrichetta','Soughton','esoughtonnf@about.me',61.5),
('Sharlene','Woodger','swoodgerng@netscape.com',39.75),
('Cordula','Unworth','cunworthnh@paginegialle.it',46.25),
('Daisie','Vigneron','dvigneronni@hibu.com',15.5),
('Thatch','Di Giacomettino','tdigiacomettinonj@blogs.com',96.0),
('Shandeigh','Rignall','srignallnk@theatlantic.com',5.25),
('Margaret','Bullier','mbulliernl@google.co.uk',0.5),
('Ashla','Polleye','apolleyenm@wsj.com',35.25),
('Woodman','Golding','wgoldingnn@indiatimes.com',86.5),
('Michaela','Mattecot','mmattecotno@youtu.be',53.0),
('Gamaliel','Elwyn','gelwynnp@icio.us',37.25),
('Ashil','Colston','acolstonnq@abc.net.au',33.5),
('Paul','Popeley','ppopeleynr@prlog.org',32.5),
('Garwood','Cubbin','gcubbinns@xrea.com',86.75),
('Gusty','Downse','gdownsent@bloglines.com',75.5),
('Lily','Demicoli','ldemicolinu@hexun.com',44.5),
('Yolande','Andell','yandellnv@altervista.org',78.75),
('Rozalie','Zecchii','rzecchiinw@tinyurl.com',98.75),
('Frankie','Coghlan','fcoghlannx@seesaa.net',52.25),
('Johnathan','Cuel','jcuelny@istockphoto.com',91.25),
('Brody','Bacup','bbacupnz@oakley.com',77.75),
('Sherill','Schwandner','sschwandnero0@cnet.com',56.75),
('Ruthann','Rewcastle','rrewcastleo1@sfgate.com',32.0),
('Vonni','Cella','vcellao2@usda.gov',85.25),
('Trevor','Toogood','ttoogoodo3@behance.net',68.0),
('Phaedra','Leel','pleelo4@bbb.org',92.75),
('Johanna','Brough','jbrougho5@apple.com',48.25),
('Lexine','Bigrigg','lbigriggo6@cdbaby.com',48.25),
('Ladonna','Huikerby','lhuikerbyo7@shareasale.com',35.25),
('Heinrik','Phillps','hphillpso8@liveinternet.ru',81.75),
('Anton','Gaul','agaulo9@washington.edu',13.0),
('Nerissa','Fynn','nfynnoa@europa.eu',93.75),
('Jan','Rankmore','jrankmoreob@unc.edu',7.25),
('Ambrose','Haresnaip','aharesnaipoc@ucsd.edu',70.75),
('Carny','Chidlow','cchidlowod@walmart.com',39.75),
('Noell','Frid','nfridoe@mlb.com',93.25),
('Mose','Whaley','mwhaleyof@phpbb.com',21.75),
('Salvidor','Lacey','slaceyog@slideshare.net',64.75),
('Borg','Callum','bcallumoh@cbsnews.com',50.0),
('Brett','Dechelle','bdechelleoi@angelfire.com',43.0),
('Rik','Ferrulli','rferrullioj@cloudflare.com',12.25),
('Charis','Christauffour','cchristauffourok@arizona.edu',66.25),
('Giffer','Guinery','gguineryol@google.fr',78.0),
('Lincoln','Peacey','lpeaceyom@newyorker.com',80.25),
('Fran','Gricks','fgrickson@liveinternet.ru',25.75),
('Astrix','Muat','amuatoo@fda.gov',24.75),
('Victor','Pantin','vpantinop@nytimes.com',42.0),
('Gustavus','Elleton','gelletonoq@linkedin.com',13.5),
('Abbey','Blakeney','ablakeneyor@prweb.com',43.5),
('Trever','Peartree','tpeartreeos@goo.ne.jp',92.75),
('Erwin','Strainge','estraingeot@fotki.com',60.25),
('Delcine','Van der Veldt','dvanderveldtou@last.fm',85.25),
('Yelena','Care','ycareov@sina.com.cn',36.25),
('Ev','Clemensen','eclemensenow@tripadvisor.com',20.25),
('Willy','Collyear','wcollyearox@skype.com',39.75),
('Brooks','Lukianovich','blukianovichoy@wikipedia.org',67.0),
('Tome','Fakes','tfakesoz@businesswire.com',76.5),
('Aurora','Ciccetti','aciccettip0@delicious.com',72.25),
('Aurie','Slocomb','aslocombp1@alibaba.com',10.5),
('Moishe','Sabates','msabatesp2@storify.com',22.25),
('Euell','Detoc','edetocp3@webeden.co.uk',35.0),
('Karalee','Vowels','kvowelsp4@prnewswire.com',9.25),
('Cindy','Frantzen','cfrantzenp5@aboutads.info',83.25),
('Christa','Wagon','cwagonp6@miibeian.gov.cn',79.0),
('Jedediah','Campana','jcampanap7@devhub.com',49.75),
('Goldi','Easeman','geasemanp8@ihg.com',83.25),
('Benjamen','Synnot','bsynnotp9@jiathis.com',85.75),
('Sloan','Weber','sweberpa@admin.ch',36.0),
('Felita','Crowdy','fcrowdypb@cdc.gov',24.0),
('Lanna','Bouchard','lbouchardpc@alibaba.com',49.25),
('Lisetta','Kubiczek','lkubiczekpd@mail.ru',52.0),
('Adam','Smewin','asmewinpe@creativecommons.org',39.25),
('Levon','Marke','lmarkepf@studiopress.com',28.0),
('Rancell','Coltart','rcoltartpg@over-blog.com',91.0),
('Elna','Elt','eeltph@4shared.com',12.5),
('Domenico','Rimington','drimingtonpi@facebook.com',12.0),
('Armstrong','Gradon','agradonpj@chronoengine.com',84.75),
('Ranice','Coldham','rcoldhampk@google.com.br',19.75),
('Mallorie','Grosvener','mgrosvenerpl@elpais.com',36.25),
('Edsel','Vasilyevski','evasilyevskipm@usgs.gov',55.0),
('Irena','Smissen','ismissenpn@howstuffworks.com',32.75),
('Nixie','Grange','ngrangepo@vkontakte.ru',89.25),
('Donn','Canadine','dcanadinepp@uiuc.edu',32.25),
('Uriah','Elcoat','uelcoatpq@skyrock.com',1.25),
('Zacharias','Cordero','zcorderopr@patch.com',97.25),
('Adham','Couve','acouveps@wufoo.com',94.5),
('Sauncho','McArthur','smcarthurpt@yandex.ru',81.25),
('Mariam','Dudney','mdudneypu@youtu.be',23.5),
('Julina','Penhallurick','jpenhallurickpv@reuters.com',6.5),
('Caren','Macieja','cmaciejapw@dmoz.org',49.25),
('Zea','Sammes','zsammespx@behance.net',48.5),
('Ashlin','Zoppo','azoppopy@ocn.ne.jp',1.25),
('Ruthi','Pizey','rpizeypz@ucoz.com',13.0),
('Quincy','Manifield','qmanifieldq0@mail.ru',20.25),
('Odell','Esslement','oesslementq1@github.io',61.25),
('Arlyne','Scruton','ascrutonq2@weather.com',34.25),
('Matilda','Berggren','mberggrenq3@desdev.cn',92.25),
('Skipper','Halstead','shalsteadq4@telegraph.co.uk',55.75),
('Saidee','Eveleigh','seveleighq5@engadget.com',26.0),
('Fina','Tal','ftalq6@washington.edu',1.25),
('Ebba','Wenham','ewenhamq7@cocolog-nifty.com',23.75),
('Georgina','Ciric','gciricq8@redcross.org',87.75),
('Hedy','Peddowe','hpeddoweq9@miitbeian.gov.cn',68.5),
('Angie','Shenton','ashentonqa@va.gov',56.0),
('Gael','Fynn','gfynnqb@goo.ne.jp',53.5),
('Nerty','Rove','nroveqc@printfriendly.com',12.5),
('Sibeal','Culley','sculleyqd@devhub.com',18.0),
('Viola','Moorfield','vmoorfieldqe@weibo.com',14.75),
('Ferris','Di Ruggiero','fdiruggieroqf@techcrunch.com',8.5),
('Derwin','Switzer','dswitzerqg@google.ca',80.0),
('Vail','Simonetti','vsimonettiqh@mozilla.org',34.0),
('Sax','De Goey','sdegoeyqi@nytimes.com',72.0),
('Margo','Klosa','mklosaqj@cpanel.net',78.75),
('Brinn','Dewi','bdewiqk@berkeley.edu',60.25),
('Sholom','Helks','shelksql@bing.com',21.25),
('Nicolle','Youll','nyoullqm@ameblo.jp',16.75),
('Zackariah','Mongenot','zmongenotqn@miitbeian.gov.cn',74.25),
('Krispin','Mothersdale','kmothersdaleqo@tinypic.com',41.75),
('Farrand','Bellamy','fbellamyqp@studiopress.com',54.0),
('Blaire','Ovise','boviseqq@ifeng.com',57.0),
('Bronnie','Pleasaunce','bpleasaunceqr@youtu.be',32.75),
('Mohammed','Crosswaite','mcrosswaiteqs@live.com',72.0),
('Eloise','Pinder','epinderqt@vimeo.com',13.5),
('Will','Swales','wswalesqu@jiathis.com',78.75),
('Lin','Grocott','lgrocottqv@icio.us',15.5),
('Hatty','Seear','hseearqw@storify.com',90.25),
('Inessa','Jery','ijeryqx@youku.com',5.5),
('Creight','Meneer','cmeneerqy@yolasite.com',44.75),
('Toma','Legh','tleghqz@t-online.de',96.5),
('Dukey','Ovize','dovizer0@springer.com',98.75),
('Brandise','Pridmore','bpridmorer1@mlb.com',66.75),
('Portia','Harman','pharmanr2@nytimes.com',83.0),
('Christiano','Finder','cfinderr3@ibm.com',94.75),
('Daphna','Randall','drandallr4@slideshare.net',28.5),
('Babbie','Cecil','bcecilr5@howstuffworks.com',47.5),
('Irene','Basson','ibassonr6@intel.com',36.5),
('Grant','Balling','gballingr7@reuters.com',40.75),
('Olenka','Haslegrave','ohaslegraver8@yahoo.co.jp',16.0),
('Dinah','Southcoat','dsouthcoatr9@addtoany.com',69.0),
('Hailey','Motherwell','hmotherwellra@skyrock.com',31.5),
('Garwood','Hazlegrove','ghazlegroverb@tiny.cc',2.75),
('Chancey','Trood','ctroodrc@omniture.com',74.5),
('Maxwell','Canty','mcantyrd@liveinternet.ru',72.0),
('Elsa','Mitie','emitiere@redcross.org',89.0),
('Lavena','Gedney','lgedneyrf@va.gov',40.0),
('Sarene','Spat','sspatrg@skype.com',30.25),
('Osborn','Piper','opiperrh@latimes.com',68.5),
('Frieda','Tenney','ftenneyri@nymag.com',34.5),
('Rosaleen','Cattini','rcattinirj@mapquest.com',79.0),
('Antonella','Whitman','awhitmanrk@hugedomains.com',16.75),
('Gabby','Morit','gmoritrl@t.co',27.25),
('Witty','Gadsden','wgadsdenrm@spiegel.de',82.5),
('Tanner','Sands-Allan','tsandsallanrn@amazon.de',47.25),
('Thomasina','Falloon','tfalloonro@oakley.com',11.25),
('Sylvan','Tenant','stenantrp@cnbc.com',74.25),
('Annis','Donn','adonnrq@cornell.edu',37.75),
('Cass','Goare','cgoarerr@vk.com',79.25);

INSERT INTO project3.location VALUES
	(default, 'Reston'),
	(default, 'Arlington'),
	(default, 'Tampa'),
	(default, 'New York City'),
	(default, 'Morgantown');


insert into project3.curriculum values
    (default, 'curriculum1', 1),
    (default, 'curriculum2', 2),
    (default, 'curriculum3', 3),
    (default, 'curriculum4', 4),
    (default, 'curriculum5', 5),
    (default, 'curriculum6', 6),
    (default, 'curriculum7', 7),
    (default, 'curriculum8', 8),
    (default, 'curriculum9', 9),
    (default, 'curriculum10', 10),
    (default, 'curriculum11', 11),
    (default, 'curriculum11', 12);

INSERT INTO project3.batch VALUES
   (default, '2020-05-04','2020-07-10',true,80,'Standard',1,1),
	(default,'2020-05-13','2020-07-22',true,80,'Standard',2,2),
	(default,'2020-05-27','2020-08-05',true,70,'Spark',3,3),
	(default,'2020-06-17','2020-08-26',false,70,'Standard',4,4),
	(default,'2020-04-29','2020-07-08',true,90,'ROCP',5,1),
	(default,'2020-04-20','2020-07-05',true,70,'ROCP',5,1),
	(default,'2020-03-20','2020-05-05',true,70,'Standard',5,1),
	(default,'2020-01-20','2020-03-05',true,70,'Spark',5,1),
	(default,'2020-06-10','2020-08-19',false,80,'CF',1,4);

	

-- Trainer: -> trainerskills -> trainer -> trainerbatch -> consent
INSERT INTO project3.trainer values(DEFAULT,'adam','king','adamking@revature.com', false);
INSERT INTO project3.trainer values(DEFAULT,'andrew','crenladge','andrew@revature.com', false),
(DEFAULT,'steven','john','stevenJ@revature.com', false),
(DEFAULT,'john','james','john@revature.com', false),
(DEFAULT,'lisa','jose','lisa@revature.com', false)
;
INSERT INTO project3.trainerskills VALUES  (1,2),
(2,3),
(3,5),
(4,6),
(5,7);

INSERT INTO project3.trainerbatch VALUES (2,1),
(1,2),
(3,3),
(4,4),
(5,4)
;

INSERT INTO project3.consent VALUES
(DEFAULT,1,1,true),
(DEFAULT,2,2,true),
(DEFAULT,3,3,true),
(DEFAULT,4,4,true);

-- Associating associates with batch
UPDATE project3.associate SET
	active=true,
	assigned_batch_id=1
WHERE last_name LIKE '%les' AND active=false;

UPDATE project3.associate SET
	active=true,
	assigned_batch_id=2
WHERE last_name LIKE '%kins' AND active=false;

UPDATE project3.associate SET
	active=true,
	assigned_batch_id=3
WHERE last_name LIKE '%oo%' AND active=false;

UPDATE project3.associate SET
	active=true,
	assigned_batch_id=4
WHERE last_name LIKE '%own%' AND active=false;

UPDATE project3.associate SET
	active=true,
	assigned_batch_id=5
WHERE last_name LIKE '%ing' AND active=false;

UPDATE project3.associate SET
	active=true,
	assigned_batch_id=6
WHERE last_name LIKE '%man' AND active=false;
